FROM node:20 AS builder

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20 AS runner

WORKDIR /app

COPY --from=builder /app ./

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER nextjs

EXPOSE 2041

ENV PORT=2041

CMD ["node", ".next/standalone/server.js"]
