export const loadData = {
  GoodsAndItems: [
    "Car(s)",
    "Car tires",
    "Alcoholic beverages",
    "Rebar",
    "Suspension beams",
    "Non-alcoholic beverages",
    "Side frame",
    "Paper",
    "Household appliances",
    "Household chemicals",
    "Wall paneling (cladding)",
    "Aerated concrete blocks",
    "Gypsum",
    "Corrugated cardboard",
    "Mushrooms",
    "Hardboard (HDF)",
    "Particle board (chipboard)",
    "Doors",
    "Home relocation",
    "Boards",
    "Wood",
    "Charcoal",
    "Railway spare parts (miscellaneous)",
    "Reinforced concrete products (RCP)",
    "Animals",
    "Grain and seeds (packaged)",
    "Grain and seeds (bulk)",
    "Toys",
    "Leather goods",
    "Metal products",
    "Rubber products",
    "Tools",
    "Cable",
    "Office supplies",
    "Bricks",
    "Carpets",
    "Wheelset",
    "Computers",
    "Confectionery",
    "Canned food",
    "Feed/food additives",
    "Groats",
    "Laminated chipboard (Laminated Particle Board)",
    "People",
    "Waste paper",
    "Furniture",
    "Medications",
    "Chalk",
    "Metal",
    "Scrap metal",
    "Rolled metal",
    "Mineral wool insulation",
    "Powdered milk",
    "Ice cream",
    "Flour",
    "Meat",
    "Petroleum products",
    "Equipment and spare parts",
    "Medical equipment",
    "Footwear",
    "Vegetables",
    "Refractory products",
    "Clothing",
    "Perfume and cosmetics",
    "Foam plastic",
    "Sand",
    "Beer",
    "Lumber",
    "Plastic",
    "Railway draft gear",
    "Pallets",
    "Food products",
    "Corrugated sheet",
    "Poultry",
    "Fish (non-living)",
    "Small consignments (LCL)",
    "Sanitary ware",
    "Sugar",
    "Consolidated cargo",
    "Juices",
    "Salt",
    "Glass and porcelain",
    "Glass containers (bottles, etc.)",
    "Construction materials",
    "Sandwich panels",
    "Consumer goods (FMCG)",
    "Tobacco products",
    "Containers and packaging",
    "Textiles",
    "Peat",
    "Vehicles",
    "Pipes",
    "Fertilizers",
    "Insulation",
    "Plywood",
    "Ferroalloys",
    "Fruits",
    "Non-hazardous chemical products",
    "Hazardous chemical products",
    "Household goods",
    "Refrigeration equipment",
    "Flowers",
    "Cement",
    "Chips",
    "Wet-salted hides",
    "Railroad ties (sleepers)",
    "Crushed stone",
    "Electronics",
    "Berries",
  ],
  ContainerTypes: [
    "20' container",
    "20' container HC (high cube)",
    "20' reefer container (refrigerated)",
    "20' tank container",
    "40' container",
    "40' container HC (high cube)",
    "40' reefer container",
    "40' reefer container HC",
    "40' tank container",
    "45' container (new)",
    "45' container (old)",
    "45' reefer container",
  ],
  Packages: [
    "Not specified",
    "In bulk",
    "Boxes",
    "Loose",
    "Pallets",
    "Packs",
    "Bags",
    "Big bags",
    "Crates",
    "Sheets",
    "Barrels",
    "Canisters",
    "Rolls",
    "Pyramid",
    "IBC containers",
    "Spools",
    "Drums",
  ],
};

export interface TrailerType {
  id: number;
  name: string;
  children: Array<{
    id: number;
    name: string;
    label: string;
  }>;
}

export const TrailerTypes = [
  {
    id: 1,
    name: "Closed + Isothermal",
    children: [
      { id: 2, name: "tarpaulin", label: "Tarpaulin" },
      { id: 3, name: "container", label: "Container" },
      { id: 4, name: "van", label: "Van" },
      { id: 5, name: "all-metal", label: "All-Metal" },
      { id: 6, name: "isothermal", label: "Isothermal" },
      {
        id: 7,
        name: "refrigerated + isothermal",
        label: "Refrigerated + Isothermal",
      },
      { id: 8, name: "refrigerator", label: "Refrigerator" },
      {
        id: 9,
        name: "refrigerator with partition",
        label: "Refrigerator with Partition",
      },
      {
        id: 10,
        name: "multi-temperature refrigerator",
        label: "Multi-Temperature Refrigerator",
      },
      {
        id: 11,
        name: "refrigerated meat transporter",
        label: "Refrigerated Meat Transporter",
      },
    ],
  },
  {
    id: 12,
    name: "All Open",
    children: [
      { id: 13, name: "flatbed", label: "Flatbed" },
      { id: 14, name: "open container", label: "Open Container" },
      { id: 15, name: "dump truck", label: "Dump Truck" },
      {
        id: 16,
        name: "shalanda (large flatbed)",
        label: "Shalanda (Large Flatbed)",
      },
      {
        id: 17,
        name: "platform without sides",
        label: "Platform without Sides",
      },
      { id: 18, name: "oversized", label: "Oversized" },
      { id: 19, name: "low-bed", label: "Low-Bed" },
      { id: 20, name: "trailer", label: "Trailer" },
      { id: 21, name: "low-bed platform", label: "Low-Bed Platform" },
      { id: 22, name: "telescopic", label: "Telescopic" },
      {
        id: 23,
        name: "beam transporter (oversized)",
        label: "Beam Transporter (Oversized)",
      },
    ],
  },
  {
    id: 24,
    name: "Special Transport",
    children: [
      { id: 25, name: "bus", label: "Bus" },
      { id: 26, name: "car transporter", label: "Car Transporter" },
      { id: 27, name: "aerial work platform", label: "Aerial Work Platform" },
      { id: 28, name: "vehicle transporter", label: "Vehicle Transporter" },
      { id: 29, name: "concrete mixer truck", label: "Concrete Mixer Truck" },
      { id: 30, name: "bitumen tanker", label: "Bitumen Tanker" },
      { id: 31, name: "fuel tanker", label: "Fuel Tanker" },
      { id: 32, name: "off-road vehicle", label: "Off-Road Vehicle" },
      { id: 33, name: "gas tanker", label: "Gas Tanker" },
      { id: 34, name: "grain truck", label: "Grain Truck" },
      { id: 35, name: "horse truck", label: "Horse Truck" },
      { id: 36, name: "container truck", label: "Container Truck" },
      { id: 37, name: "fodder truck", label: "Fodder Truck" },
      { id: 38, name: "crane", label: "Crane" },
      { id: 39, name: "log truck", label: "Log Truck" },
      { id: 40, name: "scrap metal truck", label: "Scrap Metal Truck" },
      {
        id: 41,
        name: "truck with manipulator",
        label: "Truck with Manipulator",
      },
      { id: 42, name: "minibus", label: "Minibus" },
      { id: 43, name: "flour truck", label: "Flour Truck" },
      { id: 44, name: "panel truck", label: "Panel Truck" },
      { id: 45, name: "pickup", label: "Pickup" },
      {
        id: 46,
        name: "garbage compactor truck",
        label: "Garbage Compactor Truck",
      },
      { id: 47, name: "glass transport frame", label: "Glass Transport Frame" },
      { id: 48, name: "roll transporter", label: "Roll Transporter" },
      { id: 49, name: "tractor unit", label: "Tractor Unit" },
      { id: 50, name: "cattle truck", label: "Cattle Truck" },
      { id: 51, name: "glass transporter", label: "Glass Transporter" },
      { id: 52, name: "pipe transporter", label: "Pipe Transporter" },
      { id: 53, name: "cement truck", label: "Cement Truck" },
      { id: 54, name: "tank truck", label: "Tank Truck" },
      { id: 55, name: "wood chip transporter", label: "Wood Chip Transporter" },
      { id: 56, name: "tow truck", label: "Tow Truck" },
      {
        id: 57,
        name: "passenger + cargo vehicle",
        label: "Passenger + Cargo Vehicle",
      },
      {
        id: 58,
        name: "hockey stick transporter",
        label: "Hockey Stick Transporter",
      },
      { id: 59, name: "garbage truck", label: "Garbage Truck" },
      { id: 60, name: "jumbo trailer", label: "Jumbo Trailer" },
      { id: 61, name: "20' tank container", label: "20' Tank Container" },
      { id: 62, name: "40' tank container", label: "40' Tank Container" },
      { id: 63, name: "mega trailer", label: "Mega Trailer" },
      {
        id: 64,
        name: "Doppelstock (double decker)",
        label: "Doppelstock (Double Decker)",
      },
      {
        id: 65,
        name: "Extendable semi-trailer 20'/40'",
        label: "Extendable Semi-Trailer 20'/40'",
      },
    ],
  },
];

export const LoadingUnloadingFeatures = [
  { name: "top loading" },
  { name: "side loading" },
  { name: "rear loading" },
  { name: "full side opening (tarpaulin removable)" },
  { name: "with removal of crossbars" },
  { name: "with removal of uprights" },
  { name: "without gates/doors" },
  { name: "tail lift" },
  { name: "ramps" },
  { name: "with lathing/crating" },
  { name: "with sides" },
  { name: "double-sided side loading" },
  { name: "liquid bulk (tank)" },
  { name: "electric" },
  { name: "hydraulic" },
  { name: "pneumatic" },
  { name: "diesel compressor" },
];

export const Groups = [
  {
    id: 1,
    name: "China loads group",
    members: [
      {
        id: 6,
        image: "https://i.pravatar.cc/300?u=a042581f4e29026710d",
        firstname: "Tursunboy",
        lastname: "Karimov",
        role: "Dispatcher",
      },
      {
        id: 7,
        image: "https://i.pravatar.cc/300?u=a042581f4f29026707d",
        firstname: "Shaxlo",
        lastname: "Axmedova",
        role: "Dispatcher",
      },
    ],
    owner: {
      id: 8,
      image: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
      firstname: "Ibrohim",
      lastname: "Alimjanov",
      role: "Manager",
    },
  },
  {
    id: 2,
    name: "Russian loads group",
    members: [
      {
        id: 4,
        image: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        firstname: "Shoxjaxon",
        lastname: "Jo'rayev",
        role: "Dispatcher",
      },
      {
        id: 5,
        image: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        firstname: "Sevara",
        lastname: "Nazarxon",
        role: "Dispatcher",
      },
    ],
    owner: {
      id: 8,
      image: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
      firstname: "Ibrohim",
      lastname: "Alimjanov",
      role: "Manager",
    },
  },
  {
    id: 3,
    name: "America loads group",
    members: [
      {
        id: 1,
        image: "https://i.pravatar.cc/150?u=a04258114e29026302d",
        firstname: "Botir",
        lastname: "Qodirov",
        role: "Dispatcher",
      },
      {
        id: 2,
        image: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        firstname: "Aziza",
        lastname: "Abdukarimova",
        role: "Dispatcher",
      },
      {
        id: 3,
        image: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        firstname: "Guli",
        lastname: "Asalxo'jayeva",
        role: "Dispatcher",
      },
    ],
    owner: {
      id: 8,
      image: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
      firstname: "Ibrohim",
      lastname: "Alimjanov",
      role: "Manager",
    },
  },
];

export const users = [
  {
    id: 1,
    image: "https://i.pravatar.cc/150?u=a04258114e29026302d",
    firstname: "Botir",
    lastname: "Qodirov",
    role: "Dispatcher",
  },
  {
    id: 2,
    image: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    firstname: "Aziza",
    lastname: "Abdukarimova",
    role: "Dispatcher",
  },
  {
    id: 3,
    image: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    firstname: "Guli",
    lastname: "Asalxo'jayeva",
    role: "Dispatcher",
  },
  {
    id: 4,
    image: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    firstname: "Shoxjaxon",
    lastname: "Jo'rayev",
    role: "Dispatcher",
  },
  {
    id: 5,
    image: "https://i.pravatar.cc/150?u=a04258114e29026708c",
    firstname: "Sevara",
    lastname: "Nazarxon",
    role: "Dispatcher",
  },
  {
    id: 6,
    image: "https://i.pravatar.cc/300?u=a042581f4e29026710d",
    firstname: "Tursunboy",
    lastname: "Karimov",
    role: "Dispatcher",
  },
  {
    id: 7,
    image: "https://i.pravatar.cc/300?u=a042581f4f29026707d",
    firstname: "Shaxlo",
    lastname: "Axmedova",
    role: "Dispatcher",
  },
  {
    id: 8,
    image: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
    firstname: "Ibrohim",
    lastname: "Alimjanov",
    role: "Manager",
  },
];

export const Requirements = [
  { name: "Hitch" },
  { name: "Pneumatic drive" },
  { name: "Ponies" },
];

export const Permissions = [
  { name: "TIR (International Road Transport)" },
  { name: "T1 (Customs Transit Document)" },
  { name: "CMR (Consignment Note)" },
  { name: "Medical record book" },
];
